### ISSUE TITLE
Hodnoty atributu authority v elementu <subject>

### ISSUE THREAD

**Issue by JezkovaV** [NLCR/validator-e-publikaci#10]
U e-periodik v elementu <subject> atributu _authority_ vyžadována validátorem pouze hodnota Konspekt, podle DMF jsou však v tomto atributu kromě konspektu přípustné i další hodnoty ”czenas”, ”eczenas”, ”mednas”, ”czmesh”.

**Comment by jbil7** [comment]
Na problém jsem narazil u eperiodika na úrovni ARTICLE. Jistou potíž vidím v tom, že DMF k atributu `authority` pouze říká:

> odpovídá hodnotě podpole $2 Konspektu

(DMF eperio 2.5, s. 28)

Žádné konkrétní hodnoty ale DMF nezmiňuje. Podle toho, co jsem vydedukoval z LoC, jsou zde korektní hodnoty z kontrolovaného slovníku autorit věcných témat (https://www.loc.gov/standards/sourcelist/subject.html).

Ve validatorConfigu jsem v rámci commitu fb78931 ponechal u v 2.5 očekávaný obsah prázdný, validní bude v textové hodnotě _cokoli_. Ještě kouknu, jak to vypadá ve starším DMF a na ostatních úrovních a případně taky opravím.

**Comment by JezkovaV** [comment]
Díky za kontrolu, další hodnoty jsou opravdu rozepsané jen na úrovni SUPPLEMENT. Do budoucí verze DMF zvážíme přidání hodnot i na úroveň ARTICLE.

**Comment by jbil7** [comment]
Prošel jsem všechna fDMF a problém byl pouze na úrovni ARTICLE u eperiodik. Pravidlo jsem opravil tam, kde byla povolena pouze hodnota "Konspekt" - nastavil jsem to tak, aby v takových případech procházelo vše.

Tam, kde byly definovány i ostatní hodnoty "czenas, eczenas...", jsem pravidlo zachoval.

EMonografie byly v pořádku. V některých případech jsou definovány hodnoty jako "czenas, eczenas" i přesto, že v DMF nejsou (zpravidla úroveň VOLUME). Jelikož jsou ale definovány jako `recommendedContent`, nejsou vymáhány chybovou hláškou. Pravidla jsem v takových případech ponechal beze změny.

**Comment by JezkovaV** [comment]
Zkontrolováno, validace proběhla v pořádku.
