### ISSUE TITLE
Nesprávně nastavená hodnota atributu MIMETYPE v autorskoprávních metadatech

### ISSUE THREAD

**Issue by jbil7** [NLCR/validator-e-publikaci#12]
Validátor hlásí chybu:

`Chyba: /mets:mets/mets:amdSec[./mets:rightsMD]/mets:rightsMD/mets:mdWrap/@MIMETYPE: hodnota 'text/xml' neodpovídá očekávané/doporučené hodnotě 'text/html'`

Podle nových DMF perio 2.5 a mono 3.0 je v atributu `@MIMETYPE` elementu `mets:mdWrap` očekávána hodnota `text/xml`, nikoli `text/html` jako v předchozích verzích DMF.

**Comment by JezkovaV** [comment]
Zkontrolováno, validace proběhla v pořádku.
