### ISSUE TITLE
Vyžadování elementu <shelfLocator> na úrovni ISSUE

### ISSUE THREAD

**Issue by fremrovaK** [NLCR/validator-e-publikaci#6]
DMF uvádějí element `<shelfLocator>` jako doporučený, pokud lze plnit (RA), ale validátor jeho přítomnost vyžaduje.
Týká se úrovně ISSUE u periodik.

Prosíme o opravu.

**Comment by rzeh4n** [comment]
U Validátoru e-publikací se <shelfLocator> vyskytuje jen o dmf e-monograph 2.3 na úrovní VOLUME a je nepovinný. Nejspíš se tohle týká spíše Komplexního validátoru.
Tady zavírám a přesouvám sem:
https://github.com/NLCR/komplexni-validator/issues/176

**Comment by rzeh4n** [comment]
Tak precejen ve validatoru epublikaci se ten problem taky vyskytuje.

**Comment by rzeh4n** [comment]
Opraveno ve verzi 2.2.1

**Comment by JezkovaV** [comment]
Otestováno, chyba se již ve validátoru nezobrazuje.
