### ISSUE TITLE
Validátor vyžaduje atribut type v elementu <nameIdentifier>

### ISSUE THREAD

**Issue by JezkovaV** [NLCR/validator-e-publikaci#8]
V e-mononografiích na úrovních VOLUME a u e-periodik na úrovni ARTICLE je v subelementu <nameIdentifier> validátorem vyžadován povinný atribut _type_, ač je ve všech DMF vždy maximálně s povinností MA.

**Comment by jbil7** [comment]
Pro nové fDMF (emono 3.0 a eperio 2.5) bude opraveno v rámci commitů d9306c8 (emono multivolume), 45a00c4 (emono singlevolume), fb78931 (eperio article).

**Comment by jbil7** [comment]
Provedl jsem pro jistotu revizi elementu nameIdentifier a problém se ukázal být trochu rozsáhlejší. Týkalo se i příloh, čísel a ročníků. Bude opraveno dalším commitem a to i pro předchozí verze e-mono/e-perio 2.4.

**Comment by JezkovaV** [comment]
Zkontrolováno, validace proběhla v pořádku.
