### ISSUE TITLE
Doplnění hodnot elementu <genre>

### ISSUE THREAD

**Issue by JezkovaV** [NLCR/validator-e-publikaci#9]
U e-periodik na úrovni ARTICLE v elementu <genre> atributu _type_ označuje validátor jako chybnou hodnotu „interview“. Tato hodnota je však mezi použitelnými hodnotami dle Pravidel pro popis periodik, na která DMF u tohoto elementu odkazuje. Je tedy potřeba doplnit ve validátoru chybějící hodnoty.

Momentálně platí verze Pravidel pro popis periodik 8.5 (https://standardy.ndk.cz/ndk/standardy-digitalizace/copy_of_pppperio8.5_final_15_05_23.pdf), připravována je nová verze s revidovanými a nově přidanými hodnotami.

**Comment by jbil7** [comment]
Hodnotu `interview` na úrovni ARTICLE určitě doplním do eperio 2.5. Nejsem si ale jist, zda to mám přidávat i do starších fDMF, neboť ve starších papírových DMF (2.4) není u `mods:genre/@type` odkaz do PPP. A hodnota "interview" tam nikde zmíněná není. Tam bych to tedy zatím ponechal tak jak to je.

**Comment by FilipPavcik** [comment]
Ok, súhlas. Hodnotu "interview" stačí doplniť jenom do DMF pro e-periodika 2.5.

**Comment by JezkovaV** [comment]
Zkontrolováno, validace proběhla v pořádku.
